// Auto-generated from index.html.
// DO NOT EDIT.

library dart_canvas_gallery;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import "dart:html";
import "dart:math";
import "package:web_ui/web_ui.dart";
import 'package:game_loop/game_loop_html.dart';
part '../../lib/gallery.dart';
part '../../lib/gallery_element.dart';
part '../../lib/demos/analog_clock.dart';
part '../../lib/demos/rings.dart';


// Original code


Gallery gallery;
List<String> galleryItems;

void main() {
  gallery = new Gallery();
  galleryItems = toObservable(new List<String>());
  gallery.elements.keys.forEach((i) => galleryItems.add(i));

  gallery.swapTo(galleryItems.last);
}

// Additional generated code
void init_autogenerated() {
  var __root = autogenerated.document.body;
  final __html0 = new autogenerated.Element.html('<li template="" repeat="item in galleryItems"></li>');
  var __e2, __e4, __e6;
  var __t = new autogenerated.Template(__root);
  __e2 = __root.nodes[3].nodes[1].nodes[1].nodes[1];
  __t.loop(__e2, () => galleryItems, ($list, $index, __t) {
    var item = $list[$index];
    var __e1;
    __e1 = __html0.clone(true);
    var __binding0 = __t.contentBind(() => item, false);
    __e1.nodes.addAll([new autogenerated.Text('\n            '),
        __binding0,
        new autogenerated.Text('\n          ')]);
    __t.listen(__e1.onClick, ($event) { gallery.swapTo(item); });
  __t.add(__e1);
  });
  __e4 = __root.nodes[3].nodes[3].nodes[1].nodes[0];
  var __binding3 = __t.contentBind(() => gallery.currentName, false);
  __e4.nodes.add(__binding3);
  __e6 = __root.nodes[3].nodes[3].nodes[5];
  var __binding5 = __t.contentBind(() => gallery.currentDescription, false);
  __e6.nodes.add(__binding5);
  __t.create();
  __t.insert();
}

//@ sourceMappingURL=main.dart.map